# Explicit EE source lists. Paths are relative to src/.
# source_inventory.json classifies all shipped units; audit_sources.py validates coverage.

PS2_CXX_SRC = \
	ps2/system/main.cpp \
	ps2/system/log.cpp \
	tests/smoketests/platform_boot.cpp

SIZE_OPT_CXX_SRC = $(PS2_CXX_SRC) ps2/system/core.cpp $(CORE_BOOT_CXX_SRC)

CORE_CXX_SRC = \
	neo/idlib/bv/Bounds.cpp \
	neo/idlib/bv/Box.cpp \
	neo/idlib/bv/Sphere.cpp \
	neo/idlib/CommandLink.cpp \
	neo/idlib/containers/HashIndex.cpp \
	neo/idlib/geometry/DrawVert.cpp \
	neo/idlib/geometry/JointTransform.cpp \
	neo/idlib/geometry/RenderMatrix.cpp \
	neo/idlib/geometry/Surface.cpp \
	neo/idlib/geometry/Surface_Patch.cpp \
	neo/idlib/geometry/Surface_Polytope.cpp \
	neo/idlib/geometry/Surface_SweptSpline.cpp \
	neo/idlib/geometry/TraceModel.cpp \
	neo/idlib/geometry/Winding.cpp \
	neo/idlib/geometry/Winding2D.cpp \
	neo/idlib/hashing/CRC32.cpp \
	neo/idlib/hashing/MD4.cpp \
	neo/idlib/hashing/MD5.cpp \
	neo/idlib/math/Angles.cpp \
	neo/idlib/math/Complex.cpp \
	neo/idlib/math/Lcp.cpp \
	neo/idlib/math/Math.cpp \
	neo/idlib/math/Matrix.cpp \
	neo/idlib/math/MatX.cpp \
	neo/idlib/math/Ode.cpp \
	neo/idlib/math/Plane.cpp \
	neo/idlib/math/Pluecker.cpp \
	neo/idlib/math/Polynomial.cpp \
	neo/idlib/math/Quat.cpp \
	neo/idlib/math/Rotation.cpp \
	neo/idlib/math/Simd.cpp \
	neo/idlib/math/Simd_Generic.cpp \
	neo/idlib/math/Vector.cpp \
	neo/idlib/Base64.cpp \
	neo/idlib/CmdArgs.cpp \
	neo/idlib/Lexer.cpp \
	neo/idlib/math/VecX.cpp \
	neo/idlib/ParallelJobList.cpp \
	neo/idlib/Parser.cpp \
	neo/idlib/RectAllocator.cpp \
	neo/idlib/SoftwareCache.cpp \
	neo/idlib/Str.cpp \
	neo/idlib/sys/sys_assert.cpp \
	neo/idlib/Thread.cpp \
	neo/idlib/Token.cpp \
	neo/idlib/BitMsg.cpp \
	neo/idlib/Dict.cpp \
	neo/idlib/Heap.cpp \
	neo/idlib/LangDict.cpp \
	neo/idlib/Lib.cpp \
	neo/idlib/MapFile.cpp \
	neo/idlib/Timer.cpp

CORE_FRAMEWORK_CXX_SRC = \
	neo/framework/CmdSystem.cpp \
	neo/framework/CVarSystem.cpp \
	neo/framework/File.cpp
CORE_BACKEND_CXX_SRC = \
	ps2/system/heap.cpp \
	ps2/system/core.cpp \
	ps2/system/sys.cpp
CORE_C_SRC = external/dlmalloc/dlmalloc.c
CORE_BOOT_CXX_SRC = \
	tests/smoketests/core_boot.cpp \
	tests/smoketests/idlib_tests.cpp \
	tests/smoketests/heap_tests.cpp

CAMPAIGN_CXX_SRC = \
	neo/aas/AASFile.cpp \
	neo/aas/AASFileManager.cpp \
	neo/aas/AASFile_optimize.cpp \
	neo/aas/AASFile_sample.cpp \
	neo/cm/CollisionModel_contacts.cpp \
	neo/cm/CollisionModel_contents.cpp \
	neo/cm/CollisionModel_debug.cpp \
	neo/cm/CollisionModel_files.cpp \
	neo/cm/CollisionModel_load.cpp \
	neo/cm/CollisionModel_rotate.cpp \
	neo/cm/CollisionModel_trace.cpp \
	neo/cm/CollisionModel_translate.cpp \
	neo/d3xp/AF.cpp \
	neo/d3xp/AFEntity.cpp \
	neo/d3xp/Actor.cpp \
	neo/d3xp/AimAssist.cpp \
	neo/d3xp/BrittleFracture.cpp \
	neo/d3xp/Camera.cpp \
	neo/d3xp/Entity.cpp \
	neo/d3xp/Fx.cpp \
	neo/d3xp/GameEdit.cpp \
	neo/d3xp/Game_local.cpp \
	neo/d3xp/Game_network.cpp \
	neo/d3xp/Grabber.cpp \
	neo/d3xp/IK.cpp \
	neo/d3xp/Item.cpp \
	neo/d3xp/Light.cpp \
	neo/d3xp/Misc.cpp \
	neo/d3xp/Moveable.cpp \
	neo/d3xp/Mover.cpp \
	neo/d3xp/Player.cpp \
	neo/d3xp/PlayerIcon.cpp \
	neo/d3xp/PlayerView.cpp \
	neo/d3xp/Projectile.cpp \
	neo/d3xp/Pvs.cpp \
	neo/d3xp/SecurityCamera.cpp \
	neo/d3xp/SmokeParticles.cpp \
	neo/d3xp/Sound.cpp \
	neo/d3xp/Target.cpp \
	neo/d3xp/Trigger.cpp \
	neo/d3xp/Weapon.cpp \
	neo/d3xp/WorldSpawn.cpp \
	neo/d3xp/ai/AAS.cpp \
	neo/d3xp/ai/AAS_debug.cpp \
	neo/d3xp/ai/AAS_pathing.cpp \
	neo/d3xp/ai/AAS_routing.cpp \
	neo/d3xp/ai/AI.cpp \
	neo/d3xp/ai/AI_Vagary.cpp \
	neo/d3xp/ai/AI_events.cpp \
	neo/d3xp/ai/AI_pathing.cpp \
	neo/d3xp/anim/Anim.cpp \
	neo/d3xp/anim/Anim_Blend.cpp \
	neo/d3xp/anim/Anim_Testmodel.cpp \
	neo/d3xp/gamesys/Class.cpp \
	neo/d3xp/gamesys/Event.cpp \
	neo/d3xp/gamesys/SaveGame.cpp \
	neo/d3xp/gamesys/SysCmds.cpp \
	neo/d3xp/gamesys/SysCvar.cpp \
	neo/d3xp/menus/MenuHandler.cpp \
	neo/d3xp/menus/MenuHandler_HUD.cpp \
	neo/d3xp/menus/MenuHandler_PDA.cpp \
	neo/d3xp/menus/MenuScreen.cpp \
	neo/d3xp/menus/MenuScreen_HUD.cpp \
	neo/d3xp/menus/MenuScreen_PDA_Inventory.cpp \
	neo/d3xp/menus/MenuScreen_PDA_UserData.cpp \
	neo/d3xp/menus/MenuScreen_PDA_UserEmails.cpp \
	neo/d3xp/menus/MenuScreen_PDA_VideoDisks.cpp \
	neo/d3xp/menus/MenuWidget.cpp \
	neo/d3xp/menus/MenuWidget_Button.cpp \
	neo/d3xp/menus/MenuWidget_Carousel.cpp \
	neo/d3xp/menus/MenuWidget_CommandBar.cpp \
	neo/d3xp/menus/MenuWidget_DynamicList.cpp \
	neo/d3xp/menus/MenuWidget_Help.cpp \
	neo/d3xp/menus/MenuWidget_InfoBox.cpp \
	neo/d3xp/menus/MenuWidget_ItemAssignment.cpp \
	neo/d3xp/menus/MenuWidget_List.cpp \
	neo/d3xp/menus/MenuWidget_LobbyList.cpp \
	neo/d3xp/menus/MenuWidget_MenuBar.cpp \
	neo/d3xp/menus/MenuWidget_NavBar.cpp \
	neo/d3xp/menus/MenuWidget_NavButton.cpp \
	neo/d3xp/menus/MenuWidget_PDA_AudioFiles.cpp \
	neo/d3xp/menus/MenuWidget_PDA_EmailInbox.cpp \
	neo/d3xp/menus/MenuWidget_PDA_Objective.cpp \
	neo/d3xp/menus/MenuWidget_PDA_UserData.cpp \
	neo/d3xp/menus/MenuWidget_PDA_VideoInfo.cpp \
	neo/d3xp/menus/MenuWidget_Scrollbar.cpp \
	neo/d3xp/menus/MenuWidget_Shell_SaveInfo.cpp \
	neo/d3xp/physics/Clip.cpp \
	neo/d3xp/physics/Force.cpp \
	neo/d3xp/physics/Force_Constant.cpp \
	neo/d3xp/physics/Force_Drag.cpp \
	neo/d3xp/physics/Force_Field.cpp \
	neo/d3xp/physics/Force_Grab.cpp \
	neo/d3xp/physics/Force_Spring.cpp \
	neo/d3xp/physics/Physics.cpp \
	neo/d3xp/physics/Physics_AF.cpp \
	neo/d3xp/physics/Physics_Actor.cpp \
	neo/d3xp/physics/Physics_Base.cpp \
	neo/d3xp/physics/Physics_Monster.cpp \
	neo/d3xp/physics/Physics_Parametric.cpp \
	neo/d3xp/physics/Physics_Player.cpp \
	neo/d3xp/physics/Physics_RigidBody.cpp \
	neo/d3xp/physics/Physics_Static.cpp \
	neo/d3xp/physics/Physics_StaticMulti.cpp \
	neo/d3xp/physics/Push.cpp \
	neo/d3xp/script/Script_Compiler.cpp \
	neo/d3xp/script/Script_Interpreter.cpp \
	neo/d3xp/script/Script_Program.cpp \
	neo/d3xp/script/Script_Thread.cpp \
	neo/framework/CVarSystem.cpp \
	neo/framework/CmdSystem.cpp \
	neo/framework/Common.cpp \
	neo/framework/Common_dialog.cpp \
	neo/framework/Common_load.cpp \
	neo/framework/Common_localize.cpp \
	neo/framework/Common_printf.cpp \
	neo/framework/Compressor.cpp \
	neo/framework/Console.cpp \
	neo/framework/ConsoleHistory.cpp \
	neo/framework/DebugGraph.cpp \
	neo/framework/DeclAF.cpp \
	neo/framework/DeclEntityDef.cpp \
	neo/framework/DeclFX.cpp \
	neo/framework/DeclManager.cpp \
	neo/framework/DeclPDA.cpp \
	neo/framework/DeclParticle.cpp \
	neo/framework/DeclSkin.cpp \
	neo/framework/DeclTable.cpp \
	neo/framework/DemoFile.cpp \
	neo/framework/EditField.cpp \
	neo/framework/EventLoop.cpp \
	neo/framework/File.cpp \
	neo/framework/FileSystem.cpp \
	neo/framework/File_Manifest.cpp \
	neo/framework/File_Resource.cpp \
	neo/framework/File_SaveGame.cpp \
	neo/framework/KeyInput.cpp \
	neo/framework/TokenParser.cpp \
	neo/framework/Unzip.cpp \
	neo/framework/Zip.cpp \
	neo/framework/common_frame.cpp \
	neo/idlib/Base64.cpp \
	neo/idlib/BitMsg.cpp \
	neo/idlib/CmdArgs.cpp \
	neo/idlib/CommandLink.cpp \
	neo/idlib/Dict.cpp \
	neo/idlib/Heap.cpp \
	neo/idlib/LangDict.cpp \
	neo/idlib/Lexer.cpp \
	neo/idlib/Lib.cpp \
	neo/idlib/MapFile.cpp \
	neo/idlib/ParallelJobList.cpp \
	neo/idlib/Parser.cpp \
	neo/idlib/RectAllocator.cpp \
	neo/idlib/SoftwareCache.cpp \
	neo/idlib/Str.cpp \
	neo/idlib/Thread.cpp \
	neo/idlib/Timer.cpp \
	neo/idlib/Token.cpp \
	neo/idlib/bv/Bounds.cpp \
	neo/idlib/bv/Box.cpp \
	neo/idlib/bv/Sphere.cpp \
	neo/idlib/containers/HashIndex.cpp \
	neo/idlib/geometry/DrawVert.cpp \
	neo/idlib/geometry/JointTransform.cpp \
	neo/idlib/geometry/RenderMatrix.cpp \
	neo/idlib/geometry/Surface.cpp \
	neo/idlib/geometry/Surface_Patch.cpp \
	neo/idlib/geometry/Surface_Polytope.cpp \
	neo/idlib/geometry/Surface_SweptSpline.cpp \
	neo/idlib/geometry/TraceModel.cpp \
	neo/idlib/geometry/Winding.cpp \
	neo/idlib/geometry/Winding2D.cpp \
	neo/idlib/hashing/CRC32.cpp \
	neo/idlib/hashing/MD4.cpp \
	neo/idlib/hashing/MD5.cpp \
	neo/idlib/math/Angles.cpp \
	neo/idlib/math/Complex.cpp \
	neo/idlib/math/Lcp.cpp \
	neo/idlib/math/MatX.cpp \
	neo/idlib/math/Math.cpp \
	neo/idlib/math/Matrix.cpp \
	neo/idlib/math/Ode.cpp \
	neo/idlib/math/Plane.cpp \
	neo/idlib/math/Pluecker.cpp \
	neo/idlib/math/Polynomial.cpp \
	neo/idlib/math/Quat.cpp \
	neo/idlib/math/Rotation.cpp \
	neo/idlib/math/Simd.cpp \
	neo/idlib/math/Simd_Generic.cpp \
	neo/idlib/math/VecX.cpp \
	neo/idlib/math/Vector.cpp \
	neo/idlib/sys/sys_assert.cpp \
	neo/renderer/Color/ColorSpace.cpp \
	neo/renderer/DXT/DXTDecoder.cpp \
	neo/renderer/Font.cpp \
	neo/renderer/GLMatrix.cpp \
	neo/renderer/GuiModel.cpp \
	neo/renderer/Image_files.cpp \
	neo/renderer/Image_process.cpp \
	neo/renderer/Image_program.cpp \
	neo/renderer/Interaction.cpp \
	neo/renderer/Material.cpp \
	neo/renderer/Model.cpp \
	neo/renderer/ModelDecal.cpp \
	neo/renderer/ModelManager.cpp \
	neo/renderer/ModelOverlay.cpp \
	neo/renderer/Model_beam.cpp \
	neo/renderer/Model_liquid.cpp \
	neo/renderer/Model_md3.cpp \
	neo/renderer/Model_md5.cpp \
	neo/renderer/Model_prt.cpp \
	neo/renderer/Model_sprite.cpp \
	neo/renderer/RenderEntity.cpp \
	neo/renderer/RenderWorld.cpp \
	neo/renderer/RenderWorld_defs.cpp \
	neo/renderer/RenderWorld_load.cpp \
	neo/renderer/RenderWorld_portals.cpp \
	neo/renderer/ScreenRect.cpp \
	neo/renderer/jobs/ShadowShared.cpp \
	neo/renderer/jobs/dynamicshadowvolume/DynamicShadowVolume.cpp \
	neo/renderer/jobs/prelightshadowvolume/PreLightShadowVolume.cpp \
	neo/renderer/jobs/staticshadowvolume/StaticShadowVolume.cpp \
	neo/renderer/tr_frontend_addlights.cpp \
	neo/renderer/tr_frontend_addmodels.cpp \
	neo/renderer/tr_frontend_deform.cpp \
	neo/renderer/tr_frontend_guisurf.cpp \
	neo/renderer/tr_frontend_main.cpp \
	neo/renderer/tr_frontend_subview.cpp \
	neo/renderer/tr_trace.cpp \
	neo/renderer/tr_trisurf.cpp \
	neo/sound/snd_emitter.cpp \
	neo/sound/snd_shader.cpp \
	neo/sound/snd_system.cpp \
	neo/sound/snd_world.cpp \
	neo/swf/SWF_Bitstream.cpp \
	neo/swf/SWF_Dictionary.cpp \
	neo/swf/SWF_Events.cpp \
	neo/swf/SWF_Image.cpp \
	neo/swf/SWF_Load.cpp \
	neo/swf/SWF_Main.cpp \
	neo/swf/SWF_Names.cpp \
	neo/swf/SWF_ParmList.cpp \
	neo/swf/SWF_PlaceObject.cpp \
	neo/swf/SWF_Render.cpp \
	neo/swf/SWF_ScriptFunction.cpp \
	neo/swf/SWF_ScriptObject.cpp \
	neo/swf/SWF_ScriptVar.cpp \
	neo/swf/SWF_ShapeParser.cpp \
	neo/swf/SWF_Shapes.cpp \
	neo/swf/SWF_Sounds.cpp \
	neo/swf/SWF_SpriteInstance.cpp \
	neo/swf/SWF_Sprites.cpp \
	neo/swf/SWF_Text.cpp \
	neo/swf/SWF_TextInstance.cpp \
	neo/swf/SWF_Zlib.cpp \
	neo/ui/BindWindow.cpp \
	neo/ui/ChoiceWindow.cpp \
	neo/ui/DeviceContext.cpp \
	neo/ui/EditWindow.cpp \
	neo/ui/FieldWindow.cpp \
	neo/ui/GameBearShootWindow.cpp \
	neo/ui/GameBustOutWindow.cpp \
	neo/ui/GameSSDWindow.cpp \
	neo/ui/GuiScript.cpp \
	neo/ui/ListGUI.cpp \
	neo/ui/ListWindow.cpp \
	neo/ui/RegExp.cpp \
	neo/ui/RenderWindow.cpp \
	neo/ui/SimpleWindow.cpp \
	neo/ui/SliderWindow.cpp \
	neo/ui/UserInterface.cpp \
	neo/ui/Window.cpp \
	neo/ui/Winvar.cpp

# No external C dependency is required by the initial core compile gate.
VENDOR_C_SRC =
VENDOR_CXX_SRC =
